# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-06 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('body', models.TextField(verbose_name='内容')),
                ('createtime', models.DateTimeField(verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(verbose_name='更新时间')),
            ],
            options={
                'indexes': [],
            },
        ),
    ]
