# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-06 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updatetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新时间'),
        ),
    ]
