# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-08 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160906_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(max_length=30)),
                ('photo_path', models.FileField(upload_to='./upload')),
            ],
            options={
                'indexes': [],
            },
        ),
    ]
