# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-08 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_name', models.CharField(max_length=100, unique=True)),
                ('picture_description', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='image')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
