# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-08 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160908_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='picture_name',
            new_name='des',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='picture_description',
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(upload_to='/public/image'),
        ),
    ]
