# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-08 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20160908_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='des',
            field=models.CharField(max_length=100),
        ),
    ]
