# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-12 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20160912_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(max_length=300, verbose_name='摘要'),
        ),
    ]
