# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-06 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
