# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-06 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_person_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='content',
            field=models.TextField(default=1, verbose_name='内容'),
            preserve_default=False,
        ),
    ]
