# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-09-06 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_person_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.IntegerField(verbose_name='性别'),
        ),
    ]
